version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm run build
artifacts:
  files:
    - app.zip

# This is the file that will build our application into EC2.